### ISSUE TITLE
Error during installing ZeroClipboard assets.

### ISSUE THREAD

**Issue by RuslanBahlai** [symfony-bundle/zeroclipboard-bundle#1]
Hi there! I tried to use your zeroclipboard library wrapper, and it isn't bad, but I had some errors.
First of all, documentation doesn't have any information about cURL library. AssetsInstallCommand.php file uses Curl\Curl. I installed php-curl-class https://github.com/php-curl-class/php-curl-class. After that I had another problem: when curl response returned, it's not a string, but already array, so you mustn't use json_decode anymore (AssetsInstallCommand.php file, line 110). And the last is - it will be very useful to see simple example how to use it (I had spent some time before everything worked). My little example:

/* Template */
<script type="text/javascript" src="{{ asset('bundles/zeroclipboard-assets/ZeroClipboard.js') }}"></script>

<input type="text" id="my-input" value="Text to copy"/>
<a id="copy-link" href="#">Copy link</a>
/* End template */

/* main.js */
    /* Copy to clipboard */
    ZeroClipboard.setMoviePath("/bundles/zeroclipboard-assets/ZeroClipboard.swf");
    var client = new ZeroClipboard.Client(),
        copiedText = $("#my-input").attr('value');

    client.setText( copiedText );
    /* Listener for succeed copy */
    client.addEventListener('complete', function (client, text) {
            alert("Copied text to clipboard." );
        });

    client.glue('copy-link');
/* end main.js */

Best wishes, Ruslan

**Comment by amouhzi** [comment]
Hi, let me know how you are using ZeroclipboardBundle (wrapper) . Do you installed it by composer or by downloading it?

**Comment by amouhzi** [comment]
Yes, you are right. I missed in documentation to talk about Curl library, or to add it in Composer.json.
I am not using https://github.com/php-curl-class/php-curl-class this is why it doesn't work for you. I am using https://github.com/php-mod/curl another curl wrapper.

**Comment by RuslanBahlai** [comment]
Yes, I installed it by composer: sudo composer require "symfony-bundle/zeroclipboard-bundle".
Now it's clear to me, thanks

**Comment by amouhzi** [comment]
Thank you for this issue, and for your example. I will update the composer.json and the documentation to avoid the same issue for the other users.
